version: "3.7"
services:
  observer:
    image: ocurrent/ocurrent-observer:live
    command: --slack /run/secrets/ocaml-org-deployer-slack --github-oauth /run/secrets/ocurrent-observer-oauth.json www.ocaml.org,opam.ocaml.org,images.ci.ocaml.org,deploy.ci.ocaml.org,opam-repo.ci.ocaml.org,watch.ocaml.org,staging.docs.ci.ocaml.org,docs.ci.ocaml.org,staging.ocaml.org,v2.ocaml.org
    restart: always
    volumes:
      - "observer_data:/var/lib/ocurrent-observer"
    sysctls:
      - "net.ipv4.tcp_keepalive_time=60"
    secrets:
      - ocaml-org-deployer-slack
      - ocurrent-observer-oauth.json
    networks:
      - observer

volumes:
  observer_data:

networks:
  observer:
    name: observer
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2a00:1c10:3:63b::/64
          gateway: 2a00:1c10:3:63b::1

secrets:
  ocaml-org-deployer-slack:
    file: secrets/ocaml-org-deployer-slack
  ocurrent-observer-oauth.json:
    file: secrets/ocurrent-observer-oauth.json
